feat: Add custom sorting
ruilisi/fortune-sheet pull request #400
Opened 2023-06-12 07:39 UTC by ZhengIce

feat:
   * Add custom sorting, with the option to select the sorting basis column.

2023-06-13 06:10 UTC, zyc9012 requested changes
Thanks @ZhengIce. I've added change requests. Be careful with code efficiency, naming and formatting.

2023-06-13 06:10 UTC, zyc9012 commented on packages/react/src/components/customSort/index.tsx
> +  ]);
```suggestion
  useEffect(() => {
    const list: string[] = [];
    if (isTitleChange) {
      for (let i = col_start; i <= col_end; i += 1) {
        // 判断列首是否为空
        const cell = context.luckysheetfile[sheetIndex].data?.[row_start]?.[i];
        const colHeaderValue = cell?.m || cell?.v;
        if (colHeaderValue) {
          list.push(colHeaderValue as string);
        } else {
          const ColumnChar = indexToColumnChar(i);
          list.push(`${sort.columnOperation} ${ColumnChar}`);
        }
      }
    } else {
      for (let i = col_start; i <= col_end; i += 1) {
        const ColumnChar = indexToColumnChar(i);
        list.push(ColumnChar);
      }
    }
    setRangeColChar(list);
  }, [
    col_end,
    col_start,
    context.luckysheetfile,
    isTitleChange,
    row_start,
    sheetIndex,
    sort.columnOperation,
  ]);
```

Calling state setter in a for-loop is bad practice.

2023-06-13 06:10 UTC, zyc9012 commented on packages/react/src/components/customSort/index.css
> +}
Be careful with formatting. And don't use global `td`, which may pollute other elements.

2023-06-13 06:16 UTC, ZhengIce commented
@zyc9012 Thank you, I will take note and fix my code.

2023-06-13 07:10 UTC, zyc9012 requested changes
The indentation of css files should be 2 spaces. And don't include extra empty lines.

2023-06-13 08:02 UTC, ZhengIce commented
The problem stemmed from my VS Code settings, and I have already made the necessary modifications

2023-06-14 11:54 UTC, zyc9012 requested changes
A final issue: please rename `components/customSort` to `components/CustomSort`, other than that, looks good to me.

2023-06-16 10:45 UTC, zyc9012 approved these changes
Thanks @ZhengIce

2023-06-16 10:45 UTC, merged