Upgraded to storybook 7.3.2
ruilisi/fortune-sheet pull request #470
Opened 2023-08-22 14:46 UTC by juanparati

I upgrade to storybook 7.3.2. I also fix the issue with SSL validation.

2023-08-23 03:36 UTC, zyc9012 requested changes
Thanks @juanparati for upgrading storybook 👍.

Let's also fix type deprecations in story files, something like this

```diff
diff --git a/stories/API.stories.tsx b/stories/API.stories.tsx
index a54c1aa..4a1a3b9 100644
--- a/stories/API.stories.tsx
+++ b/stories/API.stories.tsx
@@ -1,11 +1,11 @@
 import React, { useCallback, useRef, useState } from "react";
-import { ComponentMeta, ComponentStory } from "@storybook/react";
+import { Meta, StoryFn } from "@storybook/react";
 import { Workbook, WorkbookInstance } from "@fortune-sheet/react";
 import { Sheet } from "@fortune-sheet/core";
 
 export default {
   component: Workbook,
-} as ComponentMeta<typeof Workbook>;
+} as Meta<typeof Workbook>;
 
 const ApiExecContainer: React.FC<{
   onRun: () => any;
@@ -43,7 +43,7 @@ const ApiExecContainer: React.FC<{
   );
 };
 
-export const GetCellValue: ComponentStory<typeof Workbook> = () => {
+export const GetCellValue: StoryFn<typeof Workbook> = () => {
   const ref = useRef<WorkbookInstance>(null);
   const [data, setData] = useState<Sheet[]>([
     {
```

----

The default pages becomes "Docs", which is weird, could you fix that?

![image](https://github.com/ruilisi/fortune-sheet/assets/3034310/5dd7d7bf-c9b1-4f41-9d6c-4f8816b8fb58)

2023-08-23 03:36 UTC, zyc9012 commented on .storybook/main.js
> +    getAbsolutePath("@storybook/addon-links"),
I removed all the `getAbsolutePath` wraps and it still worked. Why do we need it?

2023-08-23 03:36 UTC, zyc9012 commented on babel.config.json
> +	"@babel/preset-flow",
Let's format this file

2023-08-23 03:36 UTC, zyc9012 commented on packages/core/src/modules/cell.ts
> -      // if (!_.isNil(v.spl)) {
Let's not edit files unrelated to this PR

2023-08-23 08:24 UTC, juanparati commented
@zyc9012: All changes are done:
- Reverted unrelated [28bacdb](https://github.com/ruilisi/fortune-sheet/pull/470/commits/28bacdb41ce18e9c2a28f5385ce9090ea002cdc7) and [b775c6d](https://github.com/ruilisi/fortune-sheet/pull/470/commits/b775c6dd4b209263d51d25754bf9a27b90cbad44)
- Replaced deprecated types
- Removed Docs link from storybook
- Removed "getAbsolutePath" method
- Reformatted babel.config.json

2023-08-23 08:30 UTC, zyc9012 requested changes
Thanks @juanparati 

Let's also update `Collabration.stories.tsx` and `Features.stories.tsx`

2023-08-23 08:30 UTC, zyc9012 commented on packages/core/src/modules/cell.ts
> +  if (!_.isNil(v.v) && _.includes(v.ct?.fa, "0.0")) {
Let's not introduce unrelated code here.

2023-08-24 07:26 UTC, juanparati commented
@zyc9012 : Changes made:
- Removed unrelated
- Replaced deprecated types for stories
- Replaced autodocs to "tag"

2023-08-24 08:03 UTC, zyc9012 approved these changes
Thanks @juanparati 👍

2023-08-24 08:03 UTC, merged